export const calendarTime = [
  {
    id: "1",
    time: "8:00",
    type: "morning",
  },
  {
    id: "2",
    time: "8:30",
    type: "morning",
  },
  {
    id: "3",
    time: "9:00",
    type: "morning",
  },
  {
    id: "4",
    time: "9:30",
    type: "morning",
  },
  {
    id: "5",
    time: "10:00",
    type: "morning",
  },
  {
    id: "6",
    time: "10:30",
    type: "morning",
  },
  {
    id: "7",
    time: "11:00",
    type: "morning",
  },
  {
    id: "8",
    time: "11:30",
    type: "morning",
  },
  {
    id: "9",
    time: "12:00",
    type: "morning",
  },
  {
    id: "10",
    time: "13:00",
    type: "noon",
  },
  {
    id: "11",
    time: "13:30",
    type: "noon",
  },
  {
    id: "12",
    time: "14:00",
    type: "noon",
  },
  {
    id: "13",
    time: "14:30",
    type: "noon",
  },
  {
    id: "14",
    time: "15:00",
    type: "noon",
  },
  {
    id: "15",
    time: "15:30",
    type: "noon",
  },
  {
    id: "16",
    time: "16:00",
    type: "noon",
  },
  {
    id: "17",
    time: "16:30",
    type: "noon",
  },
  {
    id: "18",
    time: "17:00",
    type: "noon",
  },
  {
    id: "19",
    time: "18:00",
    type: "night",
  },
  {
    id: "20",
    time: "18:30",
    type: "night",
  },
  {
    id: "21",
    time: "19:00",
    type: "night",
  },
  {
    id: "22",
    time: "19:30",
    type: "night",
  },
  {
    id: "23",
    time: "20:00",
    type: "night",
  },
  {
    id: "24",
    time: "20:30",
    type: "night",
  },
  {
    id: "25",
    time: "21:00",
    type: "night",
  },
  {
    id: "26",
    time: "21:30",
    type: "night",
  },
  {
    id: "27",
    time: "22:00",
    type: "night",
  },
];

export const trainingContent = [
  {
    date: "12/02/2024",
    time: "9:00",
    id: "1",
    color: "#2D3748",
    class: "HCM22_FR.BA_02",
    title: "Business Foundation",
    duration: "Day 10 of 20",
    location: "HN.Fville",
    trainer: "Dinh Vu Quoc Trungccccccc",
    admin: "Ly Lien Lien Duongggggggg",
  },
  {
    date: "12/02/2024",
    time: "9:00",
    id: "2",
    color: "#285D9A",
    class: "HN22_FR_DevOps_01",
    title: "DevOps Foundation",
    duration: "Day 10 of 20",
    location: "HN.Fville",
    trainer: "Dinh Vu Quoc Trung",
    admin: "Ly Lien Lien Duong",
  },
  {
    date: "12/02/2024",
    time: "15:30",
    id: "8",
    color: "#285D9A",
    class: "HN22_FR_DevOps_01aaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    title: "DevOps Foundation",
    duration: "Day 10 of 20",
    location: "HN.Fville",
    trainer: "Dinh Vu Quoc Trung",
    admin: "Ly Lien Lien Duong",
  },
  {
    date: "12/02/2024",
    time: "9:00",
    id: "3",
    color: "#FF7568",
    class: "DN22_FR_DevOps_05",
    title: "Develop Operation Foundation",
    duration: "Day 10 of 20",
    location: "HN.Fville",
    trainer: "Dinh Vu Quoc Trung",
    admin: "Ly Lien Lien Duong",
  },
  {
    date: "12/02/2024",
    time: "10:00",
    id: "4",
    color: "#FF7568",
    class: "HN22_FR.O_DevOps_02",
    title: "DevOps",
    duration: "Day 10 of 20",
    location: "HN.Fville",
    trainer: "Dinh Vu Quoc Trung",
    admin: "Ly Lien Lien Duong",
  },
  {
    date: "12/02/2024",
    time: "15:00",
    id: "5",
    color: "#FF7568",
    class: "HN22_FR.O_DevOps_02",
    title: "DevOps",
    duration: "Day 10 of 20",
    location: "HN.Fville",
    trainer: "Dinh Vu Quoc Trung",
    admin: "Ly Lien Lien Duong",
  },
  {
    date: "12/02/2024",
    time: "15:00",
    id: "6",
    color: "#f36f21",
    class: "HN22_FR.O_DevOps_02",
    title: "DevOps",
    duration: "Day 10 of 20",
    location: "HN.Fville",
    trainer: "Dinh Vu Quoc Trung",
    admin: "Ly Lien Lien Duong",
  },
  {
    date: "12/02/2024",
    time: "22:00",
    id: "7",
    color: "#FF7568",
    class: "HN22_FR.O_DevOps_02",
    title: "DevOps",
    duration: "Day 10 of 20",
    location: "HN.Fville",
    trainer: "Dinh Vu Quoc Trung",
    admin: "Ly Lien Lien Duong",
  },
];

// export const weekTrainingContent = [
//   {
//     time: "08:00",
//     date: "03/02/2024",
//     id: "0",
//     color: "#2D3748",
//     class: "HCM22_FR.BA_02",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trungccccccc",
//     admin: "Ly Lien Lien Duongggggggg",
//   },
//   {
//     time: "09:00",
//     date: "09/03/2024",
//     id: "1",
//     color: "#285D9A",
//     class: "HN22_FR_DevOps_01",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "10:00",
//     date: "08/03/2024",
//     id: "2",
//     color: "#FF7568",
//     class: "DN22_FR_DevOps_05",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "11:00",
//     date: "07/03/2024",
//     id: "3",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "12:00",
//     date: "04/03/2024",
//     id: "4",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "08:00",
//     date: "05/03/2024",
//     id: "5",
//     color: "#f36f21",
//     class: "HN22_FR.O_DevOps_02",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "08:00",
//     date: "06/03/2024",
//     id: "6",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02aaaaaaaaaaaaaaaaaaaaaaaa",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "21:00",
//     date: "07/03/2024",
//     id: "7",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "21:00",
//     date: "08/03/2024",
//     id: "11",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "9:00",
//     date: "03/03/2024",
//     id: "8",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02aaaaaaaaaaaaaaaaaaaaaaaa",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "10:00",
//     date: "04/03/2024",
//     id: "9",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02aaaaaaaaaaaaaaaaaaaaaaaa",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "10:00",
//     date: "14/03/2024",
//     id: "10",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02aaaaaaaaaaaaaaaaaaaaaaaa",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
//   {
//     time: "12:00",
//     date: "17/03/2024",
//     id: "12",
//     color: "#FF7568",
//     class: "HN22_FR.O_DevOps_02aaaaaaaaaaaaaaaaaaaaaaaa",
//     duration: "Day 10 of 20",
//     location: "HN.Fville",
//     trainer: "Dinh Vu Quoc Trung",
//     admin: "Ly Lien Lien Duong",
//   },
// ];
