import React from "react";

const ClassContext = React.createContext({
  activeTab: 0,
  search: null,
  handleTabChange: () => {},
  handleSearch: () => {},
  classTitle: "",
  setClassTitle: () => {},
  admin: [],
  handleAdmin: () => {},
  fsu: {},
  handleFsu: () => {},
  contact: {},
  handleContact: () => {},
  trainers: [],
  handleTrainers: () => {},
  attendee: {},
  handleAttendee: () => {},
  handleSave: () => {},
  handleCancel: () => {},
  initialDays: [],
  setInitialDays: () => {},
  classData: {},
  classAdmin: [],
  fsuContact: {},
  classCode: "",
  classTime: "",
  startDate: {},
  setClassTime: () => {},
  setClassCode: () => {},
  setStartDate: () => {},
  activeStep: 0,
  setActiveStep: () => {},
  trainingProgramDetail: {},
  trainerData: {},
  fieldValidation: {},
  setFieldValidation: () => {},
  location: "",
  setLocation: () => {},
  status: "",
  setStatus: () => {},
  handleLocations: () => {},
  allTraining: [],
  handleDraft: () => {},
  isError: false,
});
export default ClassContext;
